name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set firebase credential
        run: echo "${GOOGLE_APPLICATION_CREDENTIALS}" > ./cred.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions:download_timefree
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "cred.json"
        
